
// Code generated by stanc f556d0df
#include <stan/model/model_header.hpp>
namespace spiracle_pgls_prior_predictive_model_namespace {

template <typename T, typename S>
std::vector<T> resize_to_match__(std::vector<T>& dst, const std::vector<S>& src) {
  dst.resize(src.size());
  return dst;
}

template <typename T>
Eigen::Matrix<T, -1, -1>
resize_to_match__(Eigen::Matrix<T, -1, -1>& dst, const Eigen::Matrix<T, -1, -1>& src) {
  dst.resize(src.rows(), src.cols());
  return dst;
}

template <typename T>
Eigen::Matrix<T, 1, -1>
resize_to_match__(Eigen::Matrix<T, 1, -1>& dst, const Eigen::Matrix<T, 1, -1>& src) {
  dst.resize(src.size());
  return dst;
}

template <typename T>
Eigen::Matrix<T, -1, 1>
resize_to_match__(Eigen::Matrix<T, -1, 1>& dst, const Eigen::Matrix<T, -1, 1>& src) {
  dst.resize(src.size());
  return dst;
}
std::vector<double> to_doubles__(std::initializer_list<double> x) {
  return x;
}

std::vector<stan::math::var> to_vars__(std::initializer_list<stan::math::var> x) {
  return x;
}

inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math; 

static int current_statement__ = 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 22, column 2 to column 14)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 23, column 2 to column 19)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 24, column 2 to column 15)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 26, column 2 to column 35)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 27, column 2 to column 35)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 28, column 2 to column 52)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 35, column 5 to column 32)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 33, column 8 to column 42)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 32, column 6 to line 35, column 32)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 31, column 19 to line 36, column 5)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 31, column 4 to line 36, column 5)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 30, column 17 to line 37, column 3)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 30, column 2 to line 37, column 3)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 41, column 4 to column 26)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 40, column 17 to line 42, column 3)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 40, column 2 to line 42, column 3)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 44, column 2 to column 32)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 9, column 2 to column 17)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 10, column 2 to column 14)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 11, column 2 to column 12)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 12, column 2 to column 13)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 13, column 2 to column 12)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 14, column 2 to column 13)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 15, column 2 to column 20)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 16, column 2 to column 19)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 17, column 2 to column 25)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 3, column 4 to column 25)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 4, column 4 to column 15)",
                                                      " (in 'C:/Users/jwagne/git/spiracle_scaling/spiracle_pgls_prior_predictive.stan', line 2, column 35 to line 5, column 3)"};


template <typename T0__, typename T1__, typename T2__>
typename boost::math::tools::promote_args<T0__, T1__,
T2__>::type
f(const T0__& x_i, const T1__& a, const T2__& b, std::ostream* pstream__) {
  using local_scalar_t__ = typename boost::math::tools::promote_args<T0__,
          T1__,
          T2__>::type;
  const static bool propto__ = true;
  (void) propto__;
  
  try {
    local_scalar_t__ y_i;
    
    current_statement__ = 27;
    y_i = std::numeric_limits<double>::quiet_NaN();
    current_statement__ = 27;
    y_i = ((x_i * a) + b);
    current_statement__ = 28;
    return y_i;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}

struct f_functor__ {
template <typename T0__, typename T1__, typename T2__>
typename boost::math::tools::promote_args<T0__, T1__,
T2__>::type
operator()(const T0__& x_i, const T1__& a, const T2__& b,
           std::ostream* pstream__)  const 
{
return f(x_i, a, b, pstream__);
}
};

class spiracle_pgls_prior_predictive_model : public model_base_crtp<spiracle_pgls_prior_predictive_model> {

 private:
  int pos__;
  int N;
  Eigen::Matrix<double, -1, 1> x;
  double a_mu;
  double a_sig;
  double b_mu;
  double b_sig;
  double lambda_alpha;
  double lambda_beta;
  Eigen::Matrix<double, -1, -1> cov_phylo;
 
 public:
  ~spiracle_pgls_prior_predictive_model() { }
  
  std::string model_name() const { return "spiracle_pgls_prior_predictive_model"; }
  
  spiracle_pgls_prior_predictive_model(stan::io::var_context& context__,
                                       unsigned int random_seed__ = 0,
                                       std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    typedef double local_scalar_t__;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "spiracle_pgls_prior_predictive_model_namespace::spiracle_pgls_prior_predictive_model";
    (void) function__;  // suppress unused var warning
    
    try {
      
      pos__ = 1;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      
      current_statement__ = 18;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 19;
      validate_non_negative_index("x", "N", N);
      context__.validate_dims("data initialization","x","double",
          context__.to_vec(N));
      x = Eigen::Matrix<double, -1, 1>(N);
      
      {
        std::vector<local_scalar_t__> x_flat__;
        current_statement__ = 19;
        assign(x_flat__, nil_index_list(), context__.vals_r("x"),
          "assigning variable x_flat__");
        current_statement__ = 19;
        pos__ = 1;
        current_statement__ = 19;
        for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 19;
          assign(x, cons_list(index_uni(sym1__), nil_index_list()),
            x_flat__[(pos__ - 1)], "assigning variable x");
          current_statement__ = 19;
          pos__ = (pos__ + 1);}
      }
      context__.validate_dims("data initialization","a_mu","double",
          context__.to_vec());
      
      current_statement__ = 20;
      a_mu = context__.vals_r("a_mu")[(1 - 1)];
      context__.validate_dims("data initialization","a_sig","double",
          context__.to_vec());
      
      current_statement__ = 21;
      a_sig = context__.vals_r("a_sig")[(1 - 1)];
      context__.validate_dims("data initialization","b_mu","double",
          context__.to_vec());
      
      current_statement__ = 22;
      b_mu = context__.vals_r("b_mu")[(1 - 1)];
      context__.validate_dims("data initialization","b_sig","double",
          context__.to_vec());
      
      current_statement__ = 23;
      b_sig = context__.vals_r("b_sig")[(1 - 1)];
      context__.validate_dims("data initialization","lambda_alpha","double",
          context__.to_vec());
      
      current_statement__ = 24;
      lambda_alpha = context__.vals_r("lambda_alpha")[(1 - 1)];
      context__.validate_dims("data initialization","lambda_beta","double",
          context__.to_vec());
      
      current_statement__ = 25;
      lambda_beta = context__.vals_r("lambda_beta")[(1 - 1)];
      current_statement__ = 26;
      validate_non_negative_index("cov_phylo", "N", N);
      current_statement__ = 26;
      validate_non_negative_index("cov_phylo", "N", N);
      context__.validate_dims("data initialization","cov_phylo","double",
          context__.to_vec(N, N));
      cov_phylo = Eigen::Matrix<double, -1, -1>(N, N);
      
      {
        std::vector<local_scalar_t__> cov_phylo_flat__;
        current_statement__ = 26;
        assign(cov_phylo_flat__, nil_index_list(),
          context__.vals_r("cov_phylo"),
          "assigning variable cov_phylo_flat__");
        current_statement__ = 26;
        pos__ = 1;
        current_statement__ = 26;
        for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 26;
          for (size_t sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 26;
            assign(cov_phylo,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              cov_phylo_flat__[(pos__ - 1)], "assigning variable cov_phylo");
            current_statement__ = 26;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 18;
      current_statement__ = 18;
      check_greater_or_equal(function__, "N", N, 1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename T__>
  T__ log_prob(std::vector<T__>& params_r__, std::vector<int>& params_i__,
               std::ostream* pstream__ = 0) const {
    typedef T__ local_scalar_t__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "spiracle_pgls_prior_predictive_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    
    try {
      
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob() 
    
  template <typename RNG>
  void write_array(RNG& base_rng__, std::vector<double>& params_r__,
                   std::vector<int>& params_i__, std::vector<double>& vars__,
                   bool emit_transformed_parameters__ = true,
                   bool emit_generated_quantities__ = true,
                   std::ostream* pstream__ = 0) const {
    typedef double local_scalar_t__;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "spiracle_pgls_prior_predictive_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    
    try {
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      current_statement__ = 1;
      validate_non_negative_index("y", "N", N);
      Eigen::Matrix<double, -1, 1> y;
      y = Eigen::Matrix<double, -1, 1>(N);
      
      current_statement__ = 1;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 1;
        assign(y, cons_list(index_uni(sym1__), nil_index_list()),
          std::numeric_limits<double>::quiet_NaN(), "assigning variable y");}
      current_statement__ = 2;
      validate_non_negative_index("cov", "N", N);
      current_statement__ = 2;
      validate_non_negative_index("cov", "N", N);
      Eigen::Matrix<double, -1, -1> cov;
      cov = Eigen::Matrix<double, -1, -1>(N, N);
      
      current_statement__ = 2;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 2;
        for (size_t sym2__ = 1; sym2__ <= N; ++sym2__) {
          current_statement__ = 2;
          assign(cov,
            cons_list(index_uni(sym1__),
              cons_list(index_uni(sym2__), nil_index_list())),
            std::numeric_limits<double>::quiet_NaN(),
            "assigning variable cov");}}
      current_statement__ = 3;
      validate_non_negative_index("mu", "N", N);
      Eigen::Matrix<double, -1, 1> mu;
      mu = Eigen::Matrix<double, -1, 1>(N);
      
      current_statement__ = 3;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 3;
        assign(mu, cons_list(index_uni(sym1__), nil_index_list()),
          std::numeric_limits<double>::quiet_NaN(), "assigning variable mu");
      }
      double a;
      
      current_statement__ = 4;
      a = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      a = normal_rng(a_mu, a_sig, base_rng__);
      double b;
      
      current_statement__ = 5;
      b = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      b = normal_rng(b_mu, b_sig, base_rng__);
      double lambda;
      
      current_statement__ = 6;
      lambda = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      lambda = beta_rng(lambda_alpha, lambda_beta, base_rng__);
      current_statement__ = 13;
      for (size_t i = 1; i <= N; ++i) {
        current_statement__ = 11;
        for (size_t j = 1; j <= N; ++j) {
          current_statement__ = 9;
          if (logical_eq(logical_negation(i), j)) {
            current_statement__ = 8;
            assign(cov,
              cons_list(index_uni(i),
                cons_list(index_uni(j), nil_index_list())),
              (rvalue(cov_phylo,
                 cons_list(index_uni(i),
                   cons_list(index_uni(j), nil_index_list())), "cov_phylo") *
                lambda), "assigning variable cov");
          } else {
            current_statement__ = 7;
            assign(cov,
              cons_list(index_uni(i),
                cons_list(index_uni(j), nil_index_list())),
              rvalue(cov_phylo,
                cons_list(index_uni(i),
                  cons_list(index_uni(j), nil_index_list())), "cov_phylo"),
              "assigning variable cov");
          }}}
      current_statement__ = 16;
      for (size_t i = 1; i <= N; ++i) {
        current_statement__ = 14;
        assign(mu, cons_list(index_uni(i), nil_index_list()),
          f(x[(i - 1)], a, b, pstream__), "assigning variable mu");}
      current_statement__ = 17;
      assign(y, nil_index_list(), multi_normal_rng(mu, cov, base_rng__),
        "assigning variable y");
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(y[(sym1__ - 1)]);}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (size_t sym2__ = 1; sym2__ <= N; ++sym2__) {
          vars__.push_back(
            rvalue(cov,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "cov"));}}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(mu[(sym1__ - 1)]);}
      vars__.push_back(a);
      vars__.push_back(b);
      vars__.push_back(lambda);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array() 
    
  void transform_inits(const stan::io::var_context& context__,
                       std::vector<int>& params_i__,
                       std::vector<double>& vars__, std::ostream* pstream__) const {
    typedef double local_scalar_t__;
    vars__.resize(0);
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      
      pos__ = 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits() 
    
  void get_param_names(std::vector<std::string>& names__) const {
    
    names__.resize(0);
    names__.push_back("y");
    names__.push_back("cov");
    names__.push_back("mu");
    names__.push_back("a");
    names__.push_back("b");
    names__.push_back("lambda");
    } // get_param_names() 
    
  void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.resize(0);
    std::vector<size_t> dims__;
    dims__.push_back(N);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(N);
    
    dims__.push_back(N);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(N);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dimss__.push_back(dims__);
    dims__.resize(0);
    
    } // get_dims() 
    
  void constrained_param_names(std::vector<std::string>& param_names__,
                               bool emit_transformed_parameters__ = true,
                               bool emit_generated_quantities__ = true) const {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.push_back(std::string() + "y" + '.' + std::to_string(sym1__));
        }}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          for (size_t sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.push_back(std::string() + "cov" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.push_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        }}
      param_names__.push_back(std::string() + "a");
      param_names__.push_back(std::string() + "b");
      param_names__.push_back(std::string() + "lambda");
    }
    
    } // constrained_param_names() 
    
  void unconstrained_param_names(std::vector<std::string>& param_names__,
                                 bool emit_transformed_parameters__ = true,
                                 bool emit_generated_quantities__ = true) const {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.push_back(std::string() + "y" + '.' + std::to_string(sym1__));
        }}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          for (size_t sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.push_back(std::string() + "cov" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.push_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        }}
      param_names__.push_back(std::string() + "a");
      param_names__.push_back(std::string() + "b");
      param_names__.push_back(std::string() + "lambda");
    }
    
    } // unconstrained_param_names() 
    
  std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"y\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"cov\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"a\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"b\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"lambda\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"y\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"cov\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"a\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"b\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"lambda\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool emit_transformed_parameters__ = true,
                     bool emit_generated_quantities__ = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng__, params_r_vec, params_i_vec, vars_vec,
          emit_transformed_parameters__, emit_generated_quantities__, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    template <bool propto__, bool jacobian__, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto__,jacobian__,T_>(vec_params_r, vec_params_i, pstream);
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }

};
}

typedef spiracle_pgls_prior_predictive_model_namespace::spiracle_pgls_prior_predictive_model stan_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

#endif


